# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e98eae1e3e2c870558637483cb3de5664278127f63c5280d541cc64d99a4affbaa457a88b799835c5d9ca4b45e6a34176add8f115639f6c08103e9c0c37556b1

test:
  secret_key_base: 844b6afe83f4ad09c1f11b49e0e601e0f13db8224291092cc85613bb3f7e24314c6d9df697d86c5ade7a8a4ec5a109c32f27a20934fbc7c3c6d1f30db1078e33

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
